### ISSUE TITLE
Incorrectly indents python inner classes

### ISSUE THREAD

**Issue by fyliu** [KyleKing/mdformat-mkdocs#13]
See [this issue](https://github.com/executablebooks/mdformat/issues/419) for details or I can also paste it there.

Basically, it looks like this plugin is reformatting python code blocks and doing it wrong at least for this case. The code has nested classes and it incorrectly unindented the inner class.

I have just `mdformat` and `mdformat-mkdocs` installed in a pipx environment. `mdformat` itself seems to be leaving the code block alone but the addition of `mdformat-mkdocs` is what made it reformat the block. Uninjecting the plugin doesn't stop it from happening. I had to uninstall and reinstall `mdformat` to stop it from formatting the code.

Is the reformatting behavior part of this plugin or is it picking up and using a formatter from somewhere?

I have `blacken-docs` in my pre-commit and it looks like `black` is fine with that code block. I'm just saying how other formatters behave. I'm using only commandline for testing this bug to eliminate variables. Involving `pre-commit` was what made me file the bug incorrectly in the `mdformat` project.

**Comment by KyleKing** [comment]
Thanks for posting such a detailed issue. You’ve caught me right before leave, so I’ll try to resolve before tomorrow!

**Comment by fyliu** [comment]
Wow, that's a fast response!

I didn't think to look in the source for answers and now I'm realizing and remembering reading that this project uses markdown-it. I went to look at their docs and then I'm thinking maybe it's faster for you to figure out if the problem is there or here or just me.

I'm adding mkdocs to a project that has a few other devs and mdformat feels like a great tool to enforce a level of consistency.

**Comment by fyliu** [comment]
Thanks for looking into this. I only managed to trace it to the calculate function :smile:

**Comment by KyleKing** [comment]
I think the fix will be to keep a reference to the code block indentation (last indent) when within a code block, but I ran out of time to finish the patch release.

In the interim, you could unindent the code blocks so that they aren’t part of the list and add a comment to revisit. I may not have a chance to finish the patch until next week

**Comment by fyliu** [comment]
That's fine. I'll continue to other work for now. Thanks!

I guess it's just been reformatting the code like regular content before. Just to test, I indented the input code block to 2 spaces increments and it got indented to 4 spaces in the output.

The solution probably requires skipping processing of the code block content lines until the end sequence is found rather than keeping track of the internal indents. Or maybe apply the indent adjustment from the beginning sequence line to the whole block. Just some thoughts...

**Comment by KyleKing** [comment]
Should be fixed in v1.1.1 (https://pypi.org/project/mdformat_mkdocs/#history)!

Let me know if you find any edge cases or have any issues
