### ISSUE TITLE
Handling abbreviations

### ISSUE THREAD

**Issue by pelson** [KyleKing/mdformat-mkdocs#28]
When formatting [Abbreviations](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations), such as the one in the mkdocs docs:

```
The HTML specification is maintained by the W3C.

*[HTML]: Hyper Text Markup Language
*[W3C]: World Wide Web Consortium
```

Then ``mdformat`` with ``mdformat-mkdocs`` converts them to escaped text.

Output:

```
The HTML specification is maintained by the W3C.

\*\[HTML\]: Hyper Text Markup Language
\*\[W3C\]: World Wide Web Consortium
```

I would expect this to be unchanged by ``mdformat-mkdocs``.

Tested with Python 3.11:

```
linkify-it-py   2.0.3
markdown-it-py  3.0.0
mdformat        0.7.17
mdformat_admon  2.0.3
mdformat-gfm    0.3.6
mdformat_mkdocs 2.0.11
mdformat_tables 0.4.1
mdit-py-plugins 0.4.1
mdurl           0.1.2
more-itertools  10.2.0
uc-micro-py     1.0.3
```

Additionally, I get a warning, which I don't know if it is relevant to this issue:

```
Warning: Plugin conflict. More than one plugin defined a renderer for "link" syntax.
```

**Comment by KyleKing** [comment]
Thanks for trying out this plugin and submitting such a clear bug report!

I wasn't aware of that syntax and `mdformat-mkdocs` will need to be extended to recognize it. I should have some time this weekend to take a look

**Comment by KyleKing** [comment]
I've release v2.1.0, which should address formatting Abbreviations, but rendering proper markdown will take more effort. Let me know if that release works for your needs!

**Comment by pelson** [comment]
Looks to have done the trick. Thanks!
