### ISSUE TITLE
[request] Release indent fix?

### ISSUE THREAD

**Issue by lofidevops** [KyleKing/mdformat-mkdocs#3]
If I understand correctly, https://github.com/KyleKing/mdformat-mkdocs/pull/2 includes a helpful fix for (some) indent issues, although other issues were related to `mdx-truly-sane-lists`. Would it be possible to release this fix as version 1.0.1, or something similar?

**Comment by KyleKing** [comment]
Thanks for the reminder, I just published a new release!

https://github.com/KyleKing/mdformat-mkdocs/releases/tag/v1.0.1

Let me know if you run into any issues
