### ISSUE TITLE
mdformat mkdocs 

### ISSUE THREAD

**Issue by drakeredwind01** [KyleKing/mdformat-mkdocs#37]
messed up lines:
 - 112                    extra spaces
 - 121 - 129          extra spaces
 - 174                    \- \[ \] \*\* 
 - others

[zz Pre-work Checklist DevOps-Security-Member drakeredwind01 #36 1.md](https://github.com/user-attachments/files/16629465/zz.Pre-work.Checklist.DevOps-Security-Member.drakeredwind01.36.1.md)
[zz Pre-work Checklist DevOps-Security-Member drakeredwind01 #36 2.md](https://github.com/user-attachments/files/16629466/zz.Pre-work.Checklist.DevOps-Security-Member.drakeredwind01.36.2.md)

**Comment by KyleKing** [comment]
Thanks for submitting an issue and trying out `mdformat-mkdocs`!

There are a couple of issue with the source file that need to be manually resolved before `mdformat` will know how to parse. For the below examples, I generated the HTML with the online CommonMark app: <https://spec.commonmark.org/dingus>

Markdown treats indents as part of the language (https://spec.commonmark.org/0.31.2/#indented-code-blocks). For example:

```txt
<!-- 2.md Lines 102:107 -->
- [x] Install Terraform Docs locally by following the instructions of the installation guide mentioned in [Installing Terraform docs](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#installing-terraform-docs)

    #### WINDOWS

    - if you have windows you first need [scoop](https://scoop.sh/#/)
    - run scoop command
```

Renders to HTML as a nested list in this case:

```html
<ul>
  <li>
    <p>[x] Install Terraform Docs locally by following the instructions of the installation guide mentioned in <a href="https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#installing-terraform-docs">Installing Terraform docs</a>
    </p>
    <h4>WINDOWS</h4>
    <ul>
      <li>if you have windows you first need <a href="https://scoop.sh/#/">scoop</a>
      </li>
      <li>run scoop command</li>
    </ul>
  </li>
</ul>
```

Or if line 102 had been a paragraph instead of a list, then the indented text would be rendered as a code block:

```html
<p>Text</p>
<pre>
	<code>#### WINDOWS

- if you have windows you first need [scoop](https://scoop.sh/#/)
- run scoop command
</code>
</pre>
```

Code within lists needs to be on its own line and in a fenced block (e.g. \`\`\`):

\<\!-- 2.md Lines 107:110 (unindented and code blocks moved to new lines) --\>
- run scoop command

    \`\`\`cmd
    scoop bucket add terraform-docs https://github.com/terraform-docs/scoop-bucket
    scoop install terraform-docs
    \`\`\`
    
    - if you don't have scoop run install it by running the following in powershell
        
        \`\`\`powershell
        iex (new-object net.webclient).DownloadString('https://get.scoop.sh')
        \`\`\`

        - if you get following error in red letters run the bellow command `PowerShell requires an execution policy in [Unrestricted, RemoteSigned, ByPass] to run Scoop. For example, to set the execution policy to 'RemoteSigned' please run 'Set-ExecutionPolicy RemoteSigned -Scope CurrentUser'.`

---

Renders to:

```html
<!-- 2.md Lines 107:110 (unindented and code blocks moved to new lines) -->
<ul>
  <li>
    <p>run scoop command</p>
    <pre>
			<code class="language-cmd">scoop bucket add terraform-docs https://github.com/terraform-docs/scoop-bucket
scoop install terraform-docs
</code>
		</pre>
    <ul>
      <li>
        <p>if you don't have scoop run install it by running the following in powershell</p>
        <pre>
					<code class="language-powershell">iex (new-object net.webclient).DownloadString('https://get.scoop.sh')
</code>
				</pre>
        <ul>
          <li>if you get following error in red letters run the bellow command <code>PowerShell requires an execution policy in [Unrestricted, RemoteSigned, ByPass] to run Scoop. For example, to set the execution policy to 'RemoteSigned' please run 'Set-ExecutionPolicy RemoteSigned -Scope CurrentUser'.</code>
          </li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

**Comment by KyleKing** [comment]
Oh, I think I might have misunderstood a few things:

- I see now that `1.md` is the original text
- And that the nested header within the list on line 102 was intended

With that understaning, I've pushed a formatted version of `1.md` that appears to pass `mdformat` logic for review here: https://github.com/KyleKing/mdformat-mkdocs/pull/39/files

You can see the changes I made in this diff: https://github.com/KyleKing/mdformat-mkdocs/pull/39/commits/897290716ac37e873c165370cf15962180767c8a

**Comment by KyleKing** [comment]
Also, TIL that this is valid Markdown:

- ```powershell
  iex (new-object net.webclient).DownloadString('https://get.scoop.sh')
  ```

I've created a feature request to support it, but it might be a week or two before I have time again: #40

**Comment by KyleKing** [comment]
Took awhile, but I finally have a patched version of `mdformat-mkdocs` which should correctly format the provided sample file. Let me know if you run into any additional issues. I've tested running against the original file here: https://github.com/KyleKing/mdformat-mkdocs/pull/42/commits/3a71535946e78a0aecfa81febfb395934450aad4?w=1 (using uv: #42)
