### ISSUE TITLE
Semantic line feed in bullets leading to panic with `prettier`

### ISSUE THREAD

**Issue by jamesbraza** [KyleKing/mdformat-mkdocs#4]
I am using `mdformat==0.7.16`, `mdformat-mkdocs==1.0.1`, and `prettier==3.0.0-alpha.9-for-vscode` with `tabWidth = 4` to match PEP 8.

Here is the input, and this is fine for `mdformat` and `prettier`:

```md
1. Semantic line feed where the following line is
   three spaces deep
```

However, after adding `mdformat-mkdocs`, there is a panic about the "three spaces deep" part. `mdformat-mkdocs` wants to add an extra space before "three" so it's 4-spaces deep:

```md
1. Semantic line feed where the following line is
    three spaces deep
```

I think this is a bug with `mdformat-mkdocs`, imo it shouldn't touch the semantic line feed's spacing.

**Comment by KyleKing** [comment]
Hi @jamesbraza, thanks for trying out `mdformat-mkdocs`!

I think a 3-space indent on a number list is either an intentional choice or a bug in prettier. I found one related issue that requested the behavior that `mdformat-mkdocs` implements: https://github.com/prettier/prettier/issues/5635. Is the 3-space indent a standard and documented somewhere?

**Comment by jamesbraza** [comment]
The 3-space indent on a semantic line feed gets enforced by `mdformat` without `mdformat-mkdocs`, and `prettier`.  Try running `mdformat` (without `mdformat-mkdocs`):

```md
1. Semantic line feed where the following line is
    three spaces deep
```

I think `mdformat-mkdocs` should tab over sub-bullets to 4 spaces, but should not tab over semantic line feeds to 4 spaces

**Comment by KyleKing** [comment]
Oh okay, let me take a look at making that change

**Comment by KyleKing** [comment]
So this change would break the rendering of one of my test cases. 

Based on an issue reported to mdformat https://github.com/executablebooks/mdformat/issues/371#issuecomment-1353071369, the current behavior is necessary for indented paragraphs to be identified. Below is an example:

```md
### With proposed change

1. Here indent width is
   three.

    1. Here indent width is
       three.

1. Here indent width is
   five (three). It needs to be so, because

   Otherwise this next paragraph doesn't belong in the same list item.

---

### With current behavior

1. Here indent width is
    three (four).

    1. Here indent width is
        three (four).

1. Here indent width is
    five (four). It needs to be so, because

    Otherwise this next paragraph doesn't belong in the same list item.
```

You can see that bullet 2 isn't rendered properly if we were to change the behavior:

<img width="567" alt="Screenshot 2023-06-26 at 9 09 39 PM" src="https://github.com/KyleKing/mdformat-mkdocs/assets/3784339/7eb6dc2d-5682-4a2f-8caa-f1de9aec73aa">

**Comment by jamesbraza** [comment]
Fwiw, I am not able to repro that screenshot's rendering in PyCharm:

![PyCharm rendering](https://github.com/KyleKing/mdformat-mkdocs/assets/8990777/4be2b1c6-9244-4f3d-8814-b92750daa0ab)

Or in [this](https://dillinger.io/), [this](https://markdownlivepreview.com/), or [this](https://jbt.github.io/markdown-editor/) markdown renderer.  What renderer are you using?

Fwiw, semantic linefeeds with bulleted lists is pretty fundamental to Markdown. `prettier` has been around for many years, don't you think this would have been fixed in `prettier` if it led to rendering issues?

**Comment by jamesbraza** [comment]
Looking at [the linked issue](https://github.com/executablebooks/mdformat/issues/371), I don't know there was ever actually a conclusion, hukkin in his [main response](https://github.com/executablebooks/mdformat/issues/371#issuecomment-1353071369) disagreed that it was actually a problem.  I agree with his comment here:

> indent width of ordered lists depends on the width of the initial number of the ordered list

Technically, `mdformat-mkdocs` breaks this for semantic line feeds right now.  For bullets it's not an issue.

What do you think?

**Comment by jamesbraza** [comment]
If you don't agree, perhaps `mdformat-mkdocs` could expose a boolean config option `indent_linefeeds` defaulting to `True` to control this behavior

**Comment by KyleKing** [comment]
> Fwiw, I am not able to repro that screenshot's rendering in PyCharm:
> 
> ![PyCharm rendering](https://user-images.githubusercontent.com/8990777/249028457-4be2b1c6-9244-4f3d-8814-b92750daa0ab.png)
> 
> Or in [this](https://dillinger.io/), [this](https://markdownlivepreview.com/), or [this](https://jbt.github.io/markdown-editor/) markdown renderer. What renderer are you using?
> 
> Fwiw, semantic linefeeds with bulleted lists is pretty fundamental to Markdown. `prettier` has been around for many years, don't you think this would have been fixed in `prettier` if it led to rendering issues?

I can reproduce the issue with vanilla `mkdocs` and created a minimum example here: https://github.com/KyleKing/mdformat-mkdocs/tree/464f4dfe483c602b10425d46770c2b6c4efa338a/mkdocs-demo

Just to understand, are you using this plugin with [mkdocs](https://github.com/mkdocs/mkdocs) or are you looking for 4-space support in general?

**Comment by KyleKing** [comment]
I hacked together a quick working version here: https://github.com/KyleKing/mdformat-mkdocs/commit/815e977dbf6f1c23a9f51d861249035063651cac and tested both wiht or without the configuration option here: https://github.com/KyleKing/mdformat-mkdocs/commit/7fb04767e4b70c9203f0b4a22520786418508117

~~However, I'm blocked on an approach where the user can specify the opt. Plugins can't currently extend the configuration options (see https://github.com/hukkin/mdformat-web/issues/2#issuecomment-1060062626 and https://github.com/executablebooks/mdformat/blob/0cbd2054dedf98ec8366001c8a16eacfa85cebc1/src/mdformat/_conf.py#L63-L69 and https://github.com/executablebooks/mdformat-myst/pull/9 and https://github.com/executablebooks/mdformat/issues/234)~~

Edit: looks like it should be possible to add CLI options, but not possible to extend the configuration file: https://github.com/executablebooks/mdformat/issues/378

**Comment by KyleKing** [comment]
Published! https://pypi.org/project/mdformat_mkdocs/1.0.2rc2. Try with 'mdformat_mkdocs==1.0.2rc2' however you install `mdformat`

Let me know what you think and if it is behaving properly on your projects

**Comment by jamesbraza** [comment]
Oh wow that `mdformat`'s config doesn't yet support extension, that's too bad.

My use case is actually not using MkDocs, it's just vanilla Markdown.  Long story short, we have `prettier` with `tabWidth = 4` to match [PEP 8](https://peps.python.org/pep-0008/) in our JSON, YAML and Markdown files as well.  I see `mdformat-mkdocs` as the way to get `mdformat` to indent the bullets by 4-spaces (per [this issue](https://github.com/executablebooks/mdformat/issues/317)).

---

After `pip install mdformat-mkdocs==1.0.2rc2` I see:

```shell
> mdformat --help
...
  --align-semantic-breaks-in-numbered-lists
                        If specified, align semantic indents in numbered lists to the text
```

And running, `mdformat --align-semantic-breaks-in-numbered-lists README.md` it works! 🥳 

Thank you!  I will use this in `pre-commit-config.yaml`:

```yaml
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.16
      hooks:
          - id: mdformat
            additional_dependencies:
                - ...  # Other plugins
                - mdformat-mkdocs>=1.0.2rc2
            args: [--align-semantic-breaks-in-numbered-lists]
```

**Comment by KyleKing** [comment]
That is great to hear! I'll go ahead and make the official 1.2.0 release then

Let me know if you run into any additional issues

**Comment by jamesbraza** [comment]
I think that commit has `1.2.0` and `1.0.2`, not sure which to pin

**Comment by KyleKing** [comment]
The commit and my comment were incorrect, use `1.0.2`!

https://pypi.org/project/mdformat_mkdocs/1.0.2/

**Comment by jamesbraza** [comment]
Okay cool.  Fwiw, looks like the releases and tags are out of sync somehow too, you might want to fix that

![GitHub tags](https://github.com/KyleKing/mdformat-mkdocs/assets/8990777/69c7a3c9-8b91-481b-a95c-ffc6bfc67a8e)
